spring:
  datasource:
    url: jdbc:mysql://www.dragon.com/quickstart?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: JhBl3+wvbNItQh+SfeyCnlVSvQeRNtCtu1NtM8NeHxX91MPAYQHuXEe+yLDIh3hdfvAsdiZkZW9bBIcpHEU1xw==
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
      stat-view-servlet:
        url-pattern: /druid/*
      web-stat-filter:
        url-pattern: /*

publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJMVwW59Xozo7XkEJIelIPjHUjwYwxYc6ZJVuTJki1FbS1CJtWdOkoxhdr6fZYupj2OpTQ02cNtHg0qM6ugioQECAwEAAQ==

mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  config: classpath:logback-spring.xml