server:
  port: 8082
spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: path_route
          uri: http://localhost:8081/api/hello
          predicates:
            - Path=/api/hello